Sprint 7
ClevertecFrontendLab/KononOleg pull request #5
Opened 2023-03-26 16:00 UTC by KononOleg

2023-03-26 17:11 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 74%.
Общее количество тестов: 98.
Количество непройденных тестов: 25.

2023-03-26 17:36 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 97%.
Общее количество тестов: 98.
Количество непройденных тестов: 2.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679852186/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679852186/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679852186/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679852186/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679852186/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679852186/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679852186/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679852186/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679852186/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679852186/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679852186/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679852186/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679852186/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679852186/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679852186/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679852186/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679852186/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679852186/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679852186/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679852186/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679852186/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679852186/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679852186/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679852186/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679852186/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679852186/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679852186/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679852186/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679852186/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679852186/9-app%20-burger-menu-close-768px.png)
***
**Sprint 5 -- authorization and registartion -- authorization -- success authorization (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679852186/Sprint%205%20--%20authorization%20and%20registartion%20--%20authorization%20--%20success%20authorization%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- cancel-booking -- success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679852186/Sprint%207%20--%20Profile%20functions%20tests%20--%20cancel-booking%20--%20success%20(failed).png)

2023-03-26 18:39 UTC, vvikota requested changes

2023-03-26 18:39 UTC, vvikota commented on src/components/error-message/error-message.scss
>    z-index: 30;
по возможности задаем z-index минимальные

2023-03-26 18:39 UTC, vvikota commented on src/components/header/components/burger-navigation/burger-navigation.tsx
>    const { isBurgerActive } = useAppSelector((state) => state.appSlice);
селектор формируем в сторе ,как вы делали выше

2023-03-26 18:39 UTC, vvikota commented on src/components/modal/modal.scss
>    z-index: 10;
вот z-index , вместо 10-20-30 лучше задавайте 1-2-3

2023-03-26 18:39 UTC, vvikota commented on src/components/rating/rating.tsx
> +              src={index + 1 <= rating ? StarPNG : StarEmptyPNG}
index + 1 <= rating - это условие у вас много раз повторяется в компоненте, есть смысл вынести в константу с говорящим названием, код сократится и будет более читабельный

2023-03-26 18:39 UTC, vvikota commented on src/service/acсount-service.ts
> +    return $api.get<Account>('/api/users/me');
'/api/users/me - такие пути нужны в переменные поместить
по всей папке service посмотрите)

2023-03-26 19:18 UTC, vvikota requested changes

2023-03-26 19:18 UTC, vvikota commented on cypress.config.ts
> +    screenshotsFolder: 'cypress/report/screenshots',
![image](https://user-images.githubusercontent.com/30027067/227798020-1e3292e9-953c-4381-9d9e-5cbad41c86eb.png)
при переходе в профиль менюшка осталась открытой, нужно закрывать

2023-03-26 19:18 UTC, vvikota commented on cypress.config.ts
> +    reporter: 'mochawesome',
![image](https://user-images.githubusercontent.com/30027067/227798113-ba914f25-d8ca-4be6-833a-0801845512a2.png)
сразу при переходе в профиль в поле подаствляется пароль, причем это не пароль пользователя (неверный)

далее при попытке изменения данных пользователя не меняя пароль на корректный, сменил имя и запрос на изменения завершился успешно (похоже что пароль подставился из редакса). Так явно не должно быть, при такой логике теряется смысл от этого поля с паролем. Нужно что бы в поле был введен корректный пароль и только тогда запрос завершался успешно.

2023-03-27 01:47 UTC, ValadzkoAliaksei commented on src/pages/profile/components/credentials/credentials.tsx
> +  const [focusedPassword, setFocusedPassword] = useState<boolean>(false);
не надо писать тип в лженериках, если он есть в значении по умолчанию.
тип выводится автоматом тогда

2023-03-27 04:13 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 98%.
Общее количество тестов: 98.
Количество непройденных тестов: 1.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679890435/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679890435/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679890435/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679890435/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679890435/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679890435/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679890435/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679890435/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679890435/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679890435/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679890435/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679890435/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679890435/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679890435/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679890435/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679890435/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679890435/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679890435/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679890435/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679890435/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679890435/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679890435/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679890435/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679890435/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679890435/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679890435/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679890435/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679890435/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679890435/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679890435/9-app%20-burger-menu-close-768px.png)
***
**Sprint 7 -- Profile functions tests -- cancel-booking -- success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KononOleg/1679890435/Sprint%207%20--%20Profile%20functions%20tests%20--%20cancel-booking%20--%20success%20(failed).png)

2023-03-27 09:28 UTC, ValadzkoAliaksei approved these changes

2023-03-27 09:31 UTC, vvikota approved these changes

2023-03-27 09:33 UTC, merged